# Generated by Django 4.2.26 on 2025-11-19 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PPTGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "docx_file",
                    models.FileField(
                        upload_to="uploads/docx/", verbose_name="讲稿文件"
                    ),
                ),
                (
                    "template_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/templates/",
                        verbose_name="模板文件",
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="模板名称"
                    ),
                ),
                (
                    "use_llm",
                    models.BooleanField(default=False, verbose_name="使用大模型"),
                ),
                (
                    "course_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="课程名称"
                    ),
                ),
                (
                    "college_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="学院名称"
                    ),
                ),
                (
                    "lecturer_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="讲师名称"
                    ),
                ),
                (
                    "output_ppt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="outputs/",
                        verbose_name="生成的PPT",
                    ),
                ),
                (
                    "config_json",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="configs/",
                        verbose_name="配置JSON",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "run_dir",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="运行目录"
                    ),
                ),
            ],
            options={
                "verbose_name": "PPT生成记录",
                "verbose_name_plural": "PPT生成记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
