# Generated by Django 4.2.26 on 2025-11-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppt_generator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pptgeneration",
            name="llm_api_key",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="API Key"
            ),
        ),
        migrations.AddField(
            model_name="pptgeneration",
            name="llm_base_url",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="服务器地址"
            ),
        ),
        migrations.AddField(
            model_name="pptgeneration",
            name="llm_model",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="LLM模型"
            ),
        ),
        migrations.AddField(
            model_name="pptgeneration",
            name="llm_provider",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="LLM供应商"
            ),
        ),
        migrations.AddField(
            model_name="pptgeneration",
            name="user_prompt",
            field=models.TextField(
                blank=True, null=True, verbose_name="用户自定义Prompt"
            ),
        ),
    ]
