# Generated by Django 5.2.8 on 2025-11-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ppt_generator",
            "0002_pptgeneration_llm_api_key_pptgeneration_llm_base_url_and_more",
        ),
    ]

    operations = []
