# Generated by Django 5.2.8 on 2025-11-19 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppt_generator", "0003_add_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pptgeneration",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("is_developer", "开发者权限"),
                    ("can_export_template_json", "可以导出模板JSON"),
                    ("can_view_llm_config", "可以查看LLM配置"),
                ],
                "verbose_name": "PPT生成记录",
                "verbose_name_plural": "PPT生成记录",
            },
        ),
        migrations.AddField(
            model_name="pptgeneration",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ppt_generations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
            preserve_default=False,
        ),
    ]
