# Generated by Django 5.2.8 on 2025-11-19 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppt_generator", "0004_alter_pptgeneration_options_pptgeneration_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalLLMConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        choices=[
                            ("deepseek", "DeepSeek"),
                            ("local", "本地部署模型"),
                            ("custom", "自定义服务"),
                        ],
                        default="deepseek",
                        max_length=50,
                        verbose_name="LLM供应商",
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        default="deepseek-chat",
                        help_text="例如：deepseek-chat, deepseek-reasoner, Qwen3-8B",
                        max_length=100,
                        verbose_name="LLM模型",
                    ),
                ),
                (
                    "llm_api_key",
                    models.CharField(
                        blank=True,
                        help_text="默认API密钥",
                        max_length=500,
                        verbose_name="API Key",
                    ),
                ),
                (
                    "llm_base_url",
                    models.CharField(
                        blank=True,
                        help_text="自定义服务器地址（可选）",
                        max_length=500,
                        verbose_name="服务器地址",
                    ),
                ),
                (
                    "default_prompt",
                    models.TextField(
                        blank=True,
                        help_text="全局默认的系统提示词（可选）",
                        verbose_name="默认系统Prompt",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "全局LLM配置",
                "verbose_name_plural": "全局LLM配置",
            },
        ),
    ]
