# Generated by Django 5.2.8 on 2025-11-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppt_generator", "0005_globalllmconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="pptgeneration",
            name="config_template",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="配置模板"
            ),
        ),
    ]
