# Generated by Django 5.2.8 on 2025-11-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppt_generator", "0006_pptgeneration_config_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="pptgeneration",
            name="config_template_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/config_templates/",
                verbose_name="配置模板文件",
            ),
        ),
    ]
