# Generated by Django 5.2.8 on 2025-11-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppt_generator", "0007_pptgeneration_config_template_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="globalllmconfig",
            options={
                "ordering": ["-is_default", "name"],
                "verbose_name": "全局LLM配置",
                "verbose_name_plural": "全局LLM配置",
            },
        ),
        migrations.AddField(
            model_name="globalllmconfig",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="勾选后，此配置将成为系统默认配置",
                verbose_name="默认配置",
            ),
        ),
        migrations.AddField(
            model_name="globalllmconfig",
            name="name",
            field=models.CharField(
                default="默认配置",
                help_text="为此配置起一个易于识别的名称",
                max_length=100,
                unique=True,
                verbose_name="配置名称",
            ),
            preserve_default=False,
        ),
    ]
