# Generated by Django 5.2.8 on 2025-11-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppt_generator", "0008_alter_globalllmconfig_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalllmconfig",
            name="llm_provider",
            field=models.CharField(
                choices=[
                    ("deepseek", "DeepSeek"),
                    ("taichu", "太初多模态模型"),
                    ("local", "本地部署模型"),
                    ("custom", "自定义服务"),
                ],
                default="deepseek",
                max_length=50,
                verbose_name="LLM供应商",
            ),
        ),
    ]
