# Generated by Django 5.2.8 on 2025-11-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppt_generator", "0010_alter_globalllmconfig_llm_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalllmconfig",
            name="llm_model",
            field=models.CharField(
                default="deepseek-chat",
                help_text="DeepSeek: deepseek-chat | 紫东太初: taichu_vl | 本地: 自定义模型名称",
                max_length=100,
                verbose_name="LLM模型",
            ),
        ),
    ]
