# Generated by Django 5.2.8 on 2025-11-24 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppt_generator", "0011_alter_globalllmconfig_llm_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="pptgeneration",
            name="llm_config_choice",
            field=models.CharField(
                choices=[("preset", "使用预设配置"), ("custom", "自定义配置")],
                default="preset",
                max_length=20,
                verbose_name="配置方式",
            ),
        ),
        migrations.AddField(
            model_name="pptgeneration",
            name="llm_preset_config",
            field=models.ForeignKey(
                blank=True,
                help_text="选择管理员预设的 LLM 配置",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ppt_generator.globalllmconfig",
                verbose_name="预设配置",
            ),
        ),
        migrations.AlterField(
            model_name="globalllmconfig",
            name="llm_model",
            field=models.CharField(
                default="deepseek-chat",
                help_text="DeepSeek: deepseek-chat | 紫东太初: taichu4_vl_32b | 智谱AI: glm-4.6 | 本地: 自定义模型名称",
                max_length=100,
                verbose_name="LLM模型",
            ),
        ),
        migrations.AlterField(
            model_name="globalllmconfig",
            name="llm_provider",
            field=models.CharField(
                choices=[
                    ("deepseek", "DeepSeek"),
                    ("taichu", "紫东太初多模态模型"),
                    ("glm", "智谱AI (GLM)"),
                    ("local", "本地部署模型"),
                    ("custom", "自定义服务"),
                ],
                default="deepseek",
                max_length=50,
                verbose_name="LLM供应商",
            ),
        ),
    ]
