# Generated by Django 5.2.8 on 2025-11-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppt_generator", "0012_pptgeneration_llm_config_choice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalllmconfig",
            name="is_multimodal_default",
            field=models.BooleanField(
                default=False,
                help_text="勾选后，此配置将成为多模态（图像理解）任务的默认配置，仅 glm 和 taichu 支持多模态",
                verbose_name="默认多模态配置",
            ),
        ),
    ]
