# Generated by Django 5.2.8 on 2025-11-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppt_generator", "0013_add_multimodal_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalllmconfig",
            name="supports_multimodal",
            field=models.BooleanField(
                default=False,
                help_text="勾选表示此模型支持图像理解（如 GLM-4V、Taichu-VL 等视觉模型）",
                verbose_name="支持多模态",
            ),
        ),
        migrations.AlterField(
            model_name="globalllmconfig",
            name="is_multimodal_default",
            field=models.BooleanField(
                default=False,
                help_text="勾选后，此配置将成为多模态（图像理解）任务的默认配置",
                verbose_name="默认多模态配置",
            ),
        ),
    ]
