# Generated by Django 5.2.8 on 2025-11-27 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppt_generator", "0014_add_supports_multimodal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateEditSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "editor_type",
                    models.CharField(
                        choices=[
                            ("ppt", "PPT 模板编辑器"),
                            ("config", "配置模板编辑器"),
                        ],
                        default="ppt",
                        max_length=20,
                        verbose_name="编辑器类型",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        help_text="PPT 编辑器使用 UUID，配置编辑器使用前端生成的 ID",
                        max_length=100,
                        verbose_name="会话 ID",
                    ),
                ),
                (
                    "template_name",
                    models.CharField(max_length=255, verbose_name="模板名称"),
                ),
                (
                    "progress_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="存储编辑进度，如已命名元素数、总元素数等",
                        verbose_name="编辑进度数据",
                    ),
                ),
                (
                    "thumbnail_url",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="缩略图 URL"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_edit_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "模板编辑会话",
                "verbose_name_plural": "模板编辑会话",
                "ordering": ["-updated_at"],
                "unique_together": {("user", "session_id")},
            },
        ),
    ]
