# Generated by Django 5.2.8 on 2025-11-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppt_generator", "0015_add_template_edit_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templateeditsession",
            name="editor_type",
            field=models.CharField(
                choices=[
                    ("ppt", "PPT 模板编辑器"),
                    ("config", "配置模板编辑器"),
                    ("wizard", "模板制作向导"),
                ],
                default="ppt",
                max_length=20,
                verbose_name="编辑器类型",
            ),
        ),
    ]
